-- MySQL Script generated by MySQL Workbench
-- Thu Jul 10 19:56:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8;

USE `delivery`;

-- -----------------------------------------------------
-- Table `delivery`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(30) NOT NULL,
    `lastname` VARCHAR(60) NULL,
    `birthday` DATETIME NOT NULL,
    `document` VARCHAR(14) NOT NULL,
    `email` VARCHAR(100) NULL,
    `userscol` VARCHAR(45) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `deviceToken` VARCHAR(255) NULL,
    `city` VARCHAR(45) NOT NULL,
    `status` VARCHAR(1) NOT NULL,
    `dtCreated` DATETIME DEFAULT now(),
    `dtUpdate` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `document_UNIQUE` (`document` ASC),
    UNIQUE INDEX `userscol_UNIQUE` (`userscol` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`tb_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_permission` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `status` VARCHAR(1) NULL,
    `dtCreated` DATETIME DEFAULT now(),
    `dtUpdated` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`tb_user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_user_permission` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `idUsers` INT NOT NULL,
    `idPermission` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tb_user_permission_tb_permission_idx` (`idUsers` ASC),
    INDEX `fk_tb_user_permission_tb_users1_idx` (`idPermission` ASC),
    CONSTRAINT `fk_tb_user_permission_tb_permission` FOREIGN KEY (`idUsers`) REFERENCES `delivery`.`tb_permission` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_tb_user_permission_tb_users1` FOREIGN KEY (`idPermission`) REFERENCES `delivery`.`tb_users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`establishments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`establishments` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `cnpj` VARCHAR(14) NULL,
    `celphone` VARCHAR(11) NULL,
    `description` VARCHAR(150) NULL,
    `imageUrl` VARCHAR(255) NULL,
    `latitude` VARCHAR(15) NOT NULL,
    `lomgitude` VARCHAR(15) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `addressNumber` VARCHAR(6) NOT NULL,
    `complement` VARCHAR(15) NULL,
    `sttaus` VARCHAR(1) NULL,
    `dtCreated` DATETIME DEFAULT now(),
    `dtUpdate` DATETIME DEFAULT now(),
    `tb_users_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
    INDEX `fk_establishments_tb_users1_idx` (`tb_users_id` ASC),
    CONSTRAINT `fk_establishments_tb_users1` FOREIGN KEY (`tb_users_id`) REFERENCES `delivery`.`tb_users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`td_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`td_category` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `description` VARCHAR(110) NULL,
    `status` DATETIME DEFAULT now(),
    `dtCreated` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_products` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(120) NOT NULL,
    `description` VARCHAR(200) NOT NULL,
    `value` DOUBLE NOT NULL,
    `status` VARCHAR(1) NOT NULL,
    `dtCreated` DATETIME NOT NULL,
    `dtUpdated` DATETIME NULL,
    `idCategory` INT NOT NULL,
    `idEstablishment` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tb_products_td_category1_idx` (`idCategory` ASC),
    INDEX `fk_tb_products_establishments1_idx` (`idEstablishment` ASC),
    CONSTRAINT `fk_tb_products_td_category1` FOREIGN KEY (`idCategory`) REFERENCES `delivery`.`td_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_tb_products_establishments1` FOREIGN KEY (`idEstablishment`) REFERENCES `delivery`.`establishments` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`tb_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_sales` (
    `id` INT NOT NULL,
    `status` VARCHAR(1) NOT NULL,
    `dtCreated` DATETIME DEFAULT now(),
    `dtUpdate` DATETIME NULL,
    `idUser` INT NOT NULL,
    `idProduct` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tb_sales_tb_users1_idx` (`idUser` ASC),
    INDEX `fk_tb_sales_tb_products1_idx` (`idProduct` ASC),
    CONSTRAINT `fk_tb_sales_tb_users1` FOREIGN KEY (`idUser`) REFERENCES `delivery`.`tb_users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_tb_sales_tb_products1` FOREIGN KEY (`idProduct`) REFERENCES `delivery`.`tb_products` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `delivery`.`tb_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_push` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(120) NULL,
    `description` VARCHAR(255) NOT NULL,
    `dtCreated` DATETIME NULL,
    `tb_users_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tb_push_tb_users1_idx` (`tb_users_id` ASC),
    CONSTRAINT `fk_tb_push_tb_users1` FOREIGN KEY (`tb_users_id`) REFERENCES `delivery`.`tb_users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Ao capturar o valor original
SET @OLD_SQL_MODE = @@SQL_MODE;

SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;

-- Ao restaurar
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

SET SQL_MODE = IFNULL(@OLD_SQL_MODE, '');